/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder: THREE.Mesh
    Circle: THREE.Mesh
  }
  materials: {
    ['Material.002']: THREE.MeshPhysicalMaterial
    ['Material.001']: THREE.MeshStandardMaterial
  }
}

export function FlagPost(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/HoleFlagPole.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials['Material.002']}
        position={[0, 4, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle.geometry}
        material={materials['Material.001']}
        position={[0, 6.741, -1.497]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.581, 1, 1]}
      />
    </group>
  )
}

useGLTF.preload('/holeFlagMod.glb')
