/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_0: THREE.Mesh
  }
  materials: {
    Material_0: THREE.MeshStandardMaterial
  }
}

export function GolfBallModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/GolfballCentred.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        scale={[0.2, 0.2, 0.2]}
        receiveShadow
        geometry={nodes.Mesh_0.geometry}
        material={materials.Material_0}
      />
    </group>
  )
}

useGLTF.preload('/golfball_centred.glb')
