/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Bridge_Small: THREE.Mesh
  }
  materials: {
    Wood: THREE.MeshStandardMaterial
  }
}

export function Ramp(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Ramp.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bridge_Small.geometry}
        material={materials.Wood}
        scale={100}
      />
    </group>
  )
}

useGLTF.preload('/Ramp.glb')
