/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Bridge_Small: THREE.Mesh
  }
  materials: {
    Wood: THREE.MeshStandardMaterial
  }
}

export function Ramp(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Ramp.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bridge_Small.geometry}
        material={materials.Wood}
        // position={[-0.236, 1.707, 0]}
        // rotation={[Math.PI / 2, 0.581, 0]}
        scale={100}
      />
    </group>
  )
}

useGLTF.preload('/Ramp.glb')
