/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { Text3D, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh
    Circle: THREE.Mesh
    Pfosten3: THREE.Mesh
    Schild: THREE.Mesh
    Schild1: THREE.Mesh
    Schild3: THREE.Mesh
    Pfoten1: THREE.Mesh
    Schild2: THREE.Mesh
    Pfosten2: THREE.Mesh
    Schild_2: THREE.Mesh
  }
  materials: {
    Clay: THREE.MeshBasicMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    Holz4: THREE.MeshStandardMaterial
    Wegweiser1: THREE.MeshStandardMaterial
    Wegweiser3: THREE.MeshStandardMaterial
    Wegweiser2: THREE.MeshStandardMaterial
  }
}

export function SignPostPointRight(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/signpost.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pfosten2.geometry}
        material={materials.Holz4}
        position={[0.013, 0.445, -0.055]}
        rotation={[0, 0.118, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Schild_2.geometry}
        material={materials.Wegweiser2}
        position={[0.1, 0.901, -0.015]}
        rotation={[0.124, 0.038, -0.01]}
      />
      <Text3D
        font={'/Lobster_Regular.json'}
        scale={[0.065, 0.065, 0.095]}
        position={[0.14, 0.83, 0.255]}
        castShadow
        rotation={[0, (Math.PI / 64) * 33.5, (Math.PI / 64) * 4.5]}
        curveSegments={24}
        bevelSegments={1}
        bevelEnabled
        bevelSize={0.03}
        bevelThickness={0.03}
        receiveShadow
      >
        Head-on Down!
        <meshStandardMaterial color={'white'} clipShadows={true} />
      </Text3D>
    </group>
  )
}

useGLTF.preload('/signpost.glb')
