/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { Text3D, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh
    Circle: THREE.Mesh
    Pfosten3: THREE.Mesh
    Schild: THREE.Mesh
    Schild1: THREE.Mesh
    Schild3: THREE.Mesh
    Pfoten1: THREE.Mesh
    Schild2: THREE.Mesh
    Pfosten2: THREE.Mesh
    Schild_2: THREE.Mesh
  }
  materials: {
    Clay: THREE.MeshBasicMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    Holz4: THREE.MeshStandardMaterial
    Wegweiser1: THREE.MeshStandardMaterial
    Wegweiser3: THREE.MeshStandardMaterial
    Wegweiser2: THREE.MeshStandardMaterial
  }
}

export function SignPostMultiDirection(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Signpost.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Schild1.geometry}
        material={materials.Wegweiser1}
        position={[0.096, 1.01, -0.88]}
        rotation={[-0.106, -0.081, -0.009]}
      />
      <Text3D
        font={'/LobsterRegular.json'}
        scale={[0.065, 0.065, 0.045]}
        position={[0.02, 1.25, -0.545]}
        castShadow
        rotation={[0, (Math.PI / 64) * 26.5, (Math.PI / 64) * -0.5]}
        bevelSegments={1}
        curveSegments={32}
        bevelEnabled
        bevelSize={0.04}
        bevelThickness={0.1}
        height={0.5}
        lineHeight={0.5}
        letterSpacing={0.26}
        size={1.5}
        receiveShadow
      >
        Hole 2!
        <meshStandardMaterial color={'#ffffff'} clipShadows={true} />
      </Text3D>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pfoten1.geometry}
        material={materials.Holz4}
        position={[0.003, 0.287, -0.885]}
        rotation={[0, -0.194, 0]}
      />
      <Text3D
        font={'/LobsterRegular.json'}
        scale={[0.065, 0.065, 0.07]}
        position={[0.08, 0.98, -0.655]}
        castShadow
        rotation={[0, (Math.PI / 64) * 31, (Math.PI / 64) * -0.5]}
        bevelSegments={1}
        curveSegments={32}
        bevelEnabled
        bevelSize={0.04}
        bevelThickness={0.1}
        height={0.5}
        lineHeight={0.5}
        letterSpacing={0.26}
        size={1.5}
        receiveShadow
      >
        Hole 3!
        <meshStandardMaterial color={'#ffffff'} clipShadows={true} />
      </Text3D>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Schild2.geometry}
        material={materials.Wegweiser2}
        position={[0.093, 1.268, -0.839]}
        rotation={[2.962, 0.235, 0.043]}
      />
    </group>
  )
}

useGLTF.preload('/models/Signpost.glb')
