/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Wheel_a: THREE.Mesh
    Wheel_b: THREE.Mesh
    Wheel_c: THREE.Mesh
    Wheel_d: THREE.Mesh
    Wheel_e: THREE.Mesh
    Wheel_f: THREE.Mesh
    Wheel_g: THREE.Mesh
    Wheel_h: THREE.Mesh
    Railway_carriage_d: THREE.Mesh
  }
  materials: {
    lambert3SG: THREE.MeshStandardMaterial
  }
}

export function TrainFront(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/RailwayCar.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wheel_a.geometry}
        material={materials.lambert3SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wheel_b.geometry}
        material={materials.lambert3SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wheel_c.geometry}
        material={materials.lambert3SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wheel_d.geometry}
        material={materials.lambert3SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wheel_e.geometry}
        material={materials.lambert3SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wheel_f.geometry}
        material={materials.lambert3SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wheel_g.geometry}
        material={materials.lambert3SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wheel_h.geometry}
        material={materials.lambert3SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Railway_carriage_d.geometry}
        material={materials.lambert3SG}
      />
    </group>
  )
}

useGLTF.preload('/Railway car.glb')
