/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useEffect, useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useThree, useLoader } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    BigWheels1_1: THREE.Mesh
    BigWheels1_2: THREE.Mesh
    BigWheels2_1: THREE.Mesh
    BigWheels2_2: THREE.Mesh
    BigWheels3_1: THREE.Mesh
    BigWheels3_2: THREE.Mesh
    Locomotive_1: THREE.Mesh
    Locomotive_2: THREE.Mesh
    SmallWheels1: THREE.Mesh
    SmallWheels_2: THREE.Mesh
  }
  materials: {
    Orange: THREE.MeshStandardMaterial
    Grey: THREE.MeshStandardMaterial
  }
}

export function TrainFront(props: JSX.IntrinsicElements['group']) {
  

  const { nodes, materials } = useGLTF('/models/SteamTrain.glb') as GLTFResult
  return (
    <group {...props} dispose={null} scale={[40, 40, 40]}>
      <group position={[-0.32, 0.5, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BigWheels1_1.geometry}
          material={materials.Orange}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BigWheels1_2.geometry}
          material={materials.Grey}
        />
      </group>
      <group position={[0.941, 0.5, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BigWheels2_1.geometry}
          material={materials.Orange}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BigWheels2_2.geometry}
          material={materials.Grey}
        />
      </group>
      <group position={[2.202, 0.5, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BigWheels3_1.geometry}
          material={materials.Orange}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BigWheels3_2.geometry}
          material={materials.Grey}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Locomotive_1.geometry}
          material={materials.Orange}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Locomotive_2.geometry}
          material={materials.Grey}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SmallWheels1.geometry}
        material={materials.Orange}
        position={[-2.639, 0.354, 0]}
        scale={[100, 100, 20.987]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SmallWheels_2.geometry}
        material={materials.Orange}
        position={[-1.359, 0.354, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  )
}

useGLTF.preload('/models/SteamTrain.glb')
